import { MRT_Localization } from 'material-react-table'
import { MRT_Localization_EN } from 'material-react-table/locales/en'

export const localization: MRT_Localization = {
  ...MRT_Localization_EN,
  actions: '操作',
  and: '和',
  cancel: '取消',
  changeFilterMode: '更改过滤器模式',
  changeSearchMode: '更改搜索模式',
  clearFilter: '清空过滤器',
  clearSearch: '情况搜索条件',
  clearSort: '清空排序条件',
  clickToCopy: '点击复制',
  columnActions: '列操作',
  copiedToClipboard: '已复制到剪贴板',
  dropToGroupBy: '拖放到分组',
  edit: '编辑',
  expand: '展开',
  expandAll: '展开所有',
  filterArrIncludes: '',
  filterArrIncludesAll: '',
  filterArrIncludesSome: '',
  filterBetween: '',
  filterBetweenInclusive: '',
  filterByColumn: '列过滤',
  filterContains: '列包含',
  filterEmpty: '过滤空值',
  filterEndsWith: '过滤末尾为',
  filterEquals: '过滤等于',
  filterEqualsString: '等于字符串',
  filterFuzzy: '模糊过滤',
  filterGreaterThan: '大于',
  filterGreaterThanOrEqualTo: '大于等于',
  filterInNumberRange: '数字范围',
  filterIncludesString: '包含',
  filterIncludesStringSensitive: '灵敏',
  filterLessThan: '小于',
  filterLessThanOrEqualTo: '小于等于',
  filterMode: '过滤器模式',
  filterNotEmpty: '不忽略空值',
  filterNotEquals: '不等于',
  filterStartsWith: '过滤首位为',
  filterWeakEquals: '约等于',
  filteringByColumn: '列过滤',
  goToFirstPage: '跳转到首页',
  goToLastPage: '跳转到末尾',
  goToNextPage: '跳转至下一页',
  goToPreviousPage: '跳转至上一夜',
  grab: '抓取',
  groupByColumn: '按列组合',
  groupedBy: '',
  hideAll: '隐藏所有',
  hideColumn: '隐藏字段',
  max: '',
  min: '',
  move: '移动',
  noRecordsToDisplay: '没有数据',
  noResultsFound: '未找到结果',
  of: 'of',
  or: '',
  pinToLeft: '固定到左边',
  pinToRight: '固定到右边',
  resetColumnSize: '重置列长度',
  resetOrder: '重置排列次序',
  rowActions: '行操作',
  rowNumber: '行号',
  rowNumbers: '序号',
  rowsPerPage: '每页行数',
  save: '保存',
  search: '搜索',
  select: '选择',
  selectedCountOfRowCountRowsSelected: '已选中行数',
  showAll: '选择全部',
  showAllColumns: '选择所有列',
  showHideColumns: '显示/隐藏列',
  showHideFilters: '显示过滤器',
  showHideSearch: '显示搜索栏',
  sortByColumnAsc: '按列 ASC 排序',
  sortByColumnDesc: '按列描述排序',
  sortedByColumnAsc: '',
  sortedByColumnDesc: '',
  thenBy: '',
  toggleDensity: '切换密度',
  toggleFullScreen: '切换全屏',
  toggleSelectAll: '切换选择全部',
  toggleSelectRow: '切换选择行',
  toggleVisibility: '切换可见的',
  ungroupByColumn: '取消列组合',
  unpin: '取消固定',
  unpinAll: '取消所有固定',
  unsorted: '取消排序',
}

export const localization_en: MRT_Localization = MRT_Localization_EN
